// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef PainelControle_h
#define PainelControle_h

#ifdef HAS_GRAPHINTERFACE
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
// #include <FL/Fl_Spinner.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Widget.H>

class PainelControle {
public:
  PainelControle();
private:
  Fl_Window *win;
  Fl_Group *grpMenuPrincipal;
  inline void cb_Imprimir_i(Fl_Button*, void*);
  static void cb_Imprimir(Fl_Button*, void*);
  inline void cb_Desligar_i(Fl_Button*, void*);
  static void cb_Desligar(Fl_Button*, void*);
  Fl_Group *grpImprimirArquivo;
  Fl_Output *outArquivo;
  inline void cb_outArquivo_i(Fl_Output*, void*);
  static void cb_outArquivo(Fl_Output*, void*);
  // Fl_Spinner *inCopias;
  Fl_Light_Button *btColorido;
  Fl_Light_Button *btPeB;
  Fl_Button *btImprimir;
  inline void cb_btImprimir_i(Fl_Button*, void*);
  static void cb_btImprimir(Fl_Button*, void*);
  inline void cb_Voltar_i(Fl_Button*, void*);
  static void cb_Voltar(Fl_Button*, void*);
public:
  void iniciar();
private:
  void desligar();
  void apresentarMenuImprimirArquivo();
  void apresentarMenuPrincipal();
  void imprimir();
  void escolherArquivo();
};
#endif



#endif