// generated by Fast Light User Interface Designer (fluid) version 1.0309

#ifndef WindowConstructor_h
#define WindowConstructor_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>

/**
 Class that contains the principals objets for modeling GUI
*/
class WindowConstructor {
public:
  WindowConstructor();
private:
  Fl_Double_Window *Window;
  Fl_Choice *WeakForm;
};
#endif
