// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "WindowConstructor.h"
#include<FL/Fl_File_Chooser.H>
#include <FL/Fl_Widget.H>
#include <FL/Fl_Double_Window.H>
#include<iostream>

void WindowConstructor::cb_ElasticityPositional2D_i(Fl_Menu_*, void*) {
  this->EP2D_f();
}
void WindowConstructor::cb_ElasticityPositional2D(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_ElasticityPositional2D_i(o,v);
}

Fl_Menu_Item WindowConstructor::menu_WeakForm_Menu[] = {
 {"Elasticity 2D", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Elasticity Positional 2D", 0,  (Fl_Callback*)WindowConstructor::cb_ElasticityPositional2D, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Elasticity 3D", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Elastic Truss", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Positional Truss", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Linear Beam", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Transient Elasticity 2D", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Navier Stokes", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Poisson", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Stokes", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* WindowConstructor::Elasticity2D = WindowConstructor::menu_WeakForm_Menu + 0;
Fl_Menu_Item* WindowConstructor::ElasticityPositional2D = WindowConstructor::menu_WeakForm_Menu + 1;
Fl_Menu_Item* WindowConstructor::Elasticity3D = WindowConstructor::menu_WeakForm_Menu + 2;
Fl_Menu_Item* WindowConstructor::ElasticTruss = WindowConstructor::menu_WeakForm_Menu + 3;
Fl_Menu_Item* WindowConstructor::PositionalTruss = WindowConstructor::menu_WeakForm_Menu + 4;
Fl_Menu_Item* WindowConstructor::LinearBeam = WindowConstructor::menu_WeakForm_Menu + 5;
Fl_Menu_Item* WindowConstructor::TransientElasticity2D = WindowConstructor::menu_WeakForm_Menu + 6;
Fl_Menu_Item* WindowConstructor::NavierStokes = WindowConstructor::menu_WeakForm_Menu + 7;
Fl_Menu_Item* WindowConstructor::Poisson = WindowConstructor::menu_WeakForm_Menu + 8;
Fl_Menu_Item* WindowConstructor::Stokes = WindowConstructor::menu_WeakForm_Menu + 9;

/**
 Constructor
*/
WindowConstructor::WindowConstructor() {
  { Window = new Fl_Double_Window(766, 784, "Window");
    Window->box(FL_BORDER_BOX);
    Window->user_data((void*)(this));
    { // Constains the geo and msh path, in addtion to teh WeakForm
      Container_1 = new Fl_Group(20, 30, 630, 625);
      Container_1->box(FL_BORDER_BOX);
      { msh_path_w = new Fl_Output(160, 110, 280, 35, "Input .msh Path:");
      } // Fl_Output* msh_path_w
      { geo_path_w = new Fl_Output(160, 60, 280, 35, "Input .geo Path: ");
      } // Fl_Output* geo_path_w
      { Save_paths = new Fl_Button(55, 160, 90, 25, "Save paths");
      } // Fl_Button* Save_paths
      Container_1->end();
    } // Fl_Group* Container_1
    { Container_2 = new Fl_Group(50, 210, 530, 415);
      Container_2->box(FL_BORDER_BOX);
      { WeakForm_Menu = new Fl_Choice(165, 230, 195, 25, "Weak Form: ");
        WeakForm_Menu->box(FL_BORDER_BOX);
        WeakForm_Menu->down_box(FL_BORDER_BOX);
        WeakForm_Menu->menu(menu_WeakForm_Menu);
      } // Fl_Choice* WeakForm_Menu
      { // Container for Elasticity2D
        Container_2_1 = new Fl_Group(60, 305, 410, 215);
        Container_2_1->box(FL_FLAT_BOX);
        Container_2_1->hide();
        { // Input Young Modulus for Elasticity2D
          E2D_young = new Fl_Value_Input(205, 320, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* E2D_young
        { E2D_poisson = new Fl_Value_Input(205, 360, 45, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* E2D_poisson
        { E2D_PlaneStress = new Fl_Check_Button(80, 395, 25, 25, "Plane Stress ");
          E2D_PlaneStress->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* E2D_PlaneStress
        Container_2_1->end();
      } // Fl_Group* Container_2_1
      { // Container for Elasticity2D
        Container_2_2 = new Fl_Group(60, 305, 410, 215);
        Container_2_2->box(FL_FLAT_BOX);
        Container_2_2->hide();
        { // Input Young Modulus for Elasticity2D
          EP2D_young = new Fl_Value_Input(210, 325, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* EP2D_young
        { EP2D_poisson = new Fl_Value_Input(210, 365, 45, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* EP2D_poisson
        { EP2D_PlaneStress = new Fl_Check_Button(85, 400, 25, 25, "Plane Stress ");
          EP2D_PlaneStress->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* EP2D_PlaneStress
        Container_2_2->end();
      } // Fl_Group* Container_2_2
      { // Container for Elasticity2D
        Container_2_3 = new Fl_Group(60, 305, 410, 215);
        Container_2_3->box(FL_FLAT_BOX);
        Container_2_3->hide();
        { // Input Young Modulus for Elasticity2D
          E3D_young = new Fl_Value_Input(220, 335, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* E3D_young
        { E3D_poisson = new Fl_Value_Input(220, 375, 45, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* E3D_poisson
        Container_2_3->end();
      } // Fl_Group* Container_2_3
      { // Container for Elasticity2D
        Container_2_4 = new Fl_Group(60, 305, 410, 215);
        Container_2_4->box(FL_FLAT_BOX);
        Container_2_4->hide();
        { // Input Young Modulus for Elasticity2D
          ET_young = new Fl_Value_Input(225, 340, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* ET_young
        { ET_area = new Fl_Value_Input(225, 380, 45, 25, "Area: ");
        } // Fl_Value_Input* ET_area
        Container_2_4->end();
      } // Fl_Group* Container_2_4
      { // Container for Elasticity2D
        Container_2_5 = new Fl_Group(60, 305, 410, 215);
        Container_2_5->box(FL_FLAT_BOX);
        Container_2_5->hide();
        { // Input Young Modulus for Elasticity2D
          PT_young = new Fl_Value_Input(255, 370, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* PT_young
        { PT_area = new Fl_Value_Input(255, 410, 45, 25, "Area:   ");
        } // Fl_Value_Input* PT_area
        Container_2_5->end();
      } // Fl_Group* Container_2_5
      { // Container for Elasticity2D
        Container_2_6 = new Fl_Group(60, 305, 410, 215);
        Container_2_6->box(FL_FLAT_BOX);
        Container_2_6->hide();
        { // Input Young Modulus for Elasticity2D
          LB_young = new Fl_Value_Input(255, 370, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* LB_young
        { LB_Inertia = new Fl_Value_Input(255, 410, 45, 25, "Inertia:  ");
        } // Fl_Value_Input* LB_Inertia
        Container_2_6->end();
      } // Fl_Group* Container_2_6
      { // Container for Elasticity2D
        Container_2_7 = new Fl_Group(60, 305, 410, 215);
        Container_2_7->box(FL_FLAT_BOX);
        Container_2_7->hide();
        { // Input Young Modulus for Elasticity2D
          TE2D_young = new Fl_Value_Input(225, 340, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* TE2D_young
        { TE2D_poisson = new Fl_Value_Input(225, 375, 45, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* TE2D_poisson
        { TE2D_PlaneStress = new Fl_Check_Button(100, 455, 25, 25, "Plane Stress ");
          TE2D_PlaneStress->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* TE2D_PlaneStress
        { TE2D_damping = new Fl_Value_Input(170, 405, 45, 25, "Damping: ");
        } // Fl_Value_Input* TE2D_damping
        { TE2D_density = new Fl_Value_Input(160, 430, 45, 25, "Density: ");
        } // Fl_Value_Input* TE2D_density
        Container_2_7->end();
      } // Fl_Group* Container_2_7
      Container_2->end();
    } // Fl_Group* Container_2
    Window->end();
  } // Fl_Double_Window* Window
}

void WindowConstructor::Open() {
  this->Window->show();
}

void WindowConstructor::Input_geo() {
  const char * geo_path = fl_file_chooser(".geo file path", "*.geo*", "", 0);
  
  this->geo_path_w->value(geo_path);
}

void WindowConstructor::EP2D_f() {
  this->Container_2_2->show();
}
