// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "WindowConstructor.h"

#ifdef HAS_GRAPHINTERFACE


#include<FL/Fl_File_Chooser.H>
#include<iostream>

void WindowConstructor::cb_msh_path_i(Fl_Output*, void*) {
  this->Input_msh_f();
}
void WindowConstructor::cb_msh_path(Fl_Output* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_msh_path_i(o,v);
}

void WindowConstructor::cb_geo_path_i(Fl_Output*, void*) {
  this->Input_geo_f();
}
void WindowConstructor::cb_geo_path(Fl_Output* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_geo_path_i(o,v);
}

void WindowConstructor::cb_Elasticity2D_i(Fl_Menu_*, void*) {
  this->WF1_f();
}
void WindowConstructor::cb_Elasticity2D(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_Elasticity2D_i(o,v);
}

void WindowConstructor::cb_ElasticityPositional2D_i(Fl_Menu_*, void*) {
  this->WF2_f();
}
void WindowConstructor::cb_ElasticityPositional2D(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_ElasticityPositional2D_i(o,v);
}

void WindowConstructor::cb_Elasticity3D_i(Fl_Menu_*, void*) {
  this->WF3_f();
}
void WindowConstructor::cb_Elasticity3D(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_Elasticity3D_i(o,v);
}

void WindowConstructor::cb_ElasticTruss_i(Fl_Menu_*, void*) {
  this->WF4_f();
}
void WindowConstructor::cb_ElasticTruss(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_ElasticTruss_i(o,v);
}

void WindowConstructor::cb_PositionalTruss_i(Fl_Menu_*, void*) {
  this->WF5_f();
}
void WindowConstructor::cb_PositionalTruss(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_PositionalTruss_i(o,v);
}

void WindowConstructor::cb_Stokes_i(Fl_Menu_*, void*) {
  this->WF6_f();
}
void WindowConstructor::cb_Stokes(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_Stokes_i(o,v);
}

void WindowConstructor::cb_NavierStokes_i(Fl_Menu_*, void*) {
  this->WF7_f();
}
void WindowConstructor::cb_NavierStokes(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_NavierStokes_i(o,v);
}

void WindowConstructor::cb_Poisson_i(Fl_Menu_*, void*) {
  this->WF8_f();
}
void WindowConstructor::cb_Poisson(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_Poisson_i(o,v);
}

void WindowConstructor::cb_L2Projection_i(Fl_Menu_*, void*) {
  this->WF9_f();
}
void WindowConstructor::cb_L2Projection(Fl_Menu_* o, void* v) {
  ((WindowConstructor*)(o->parent()->parent()->user_data()))->cb_L2Projection_i(o,v);
}

Fl_Menu_Item WindowConstructor::menu_WeakForm_Menu[] = {
 {"Elasticity 2D", 0,  (Fl_Callback*)WindowConstructor::cb_Elasticity2D, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Elasticity Positional 2D", 0,  (Fl_Callback*)WindowConstructor::cb_ElasticityPositional2D, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Elasticity 3D", 0,  (Fl_Callback*)WindowConstructor::cb_Elasticity3D, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Elastic Truss", 0,  (Fl_Callback*)WindowConstructor::cb_ElasticTruss, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Positional Truss", 0,  (Fl_Callback*)WindowConstructor::cb_PositionalTruss, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Stokes", 0,  (Fl_Callback*)WindowConstructor::cb_Stokes, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Navier Stokes", 0,  (Fl_Callback*)WindowConstructor::cb_NavierStokes, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Poisson", 0,  (Fl_Callback*)WindowConstructor::cb_Poisson, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"L2Projection", 0,  (Fl_Callback*)WindowConstructor::cb_L2Projection, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* WindowConstructor::Elasticity2D = WindowConstructor::menu_WeakForm_Menu + 0;
Fl_Menu_Item* WindowConstructor::ElasticityPositional2D = WindowConstructor::menu_WeakForm_Menu + 1;
Fl_Menu_Item* WindowConstructor::Elasticity3D = WindowConstructor::menu_WeakForm_Menu + 2;
Fl_Menu_Item* WindowConstructor::ElasticTruss = WindowConstructor::menu_WeakForm_Menu + 3;
Fl_Menu_Item* WindowConstructor::PositionalTruss = WindowConstructor::menu_WeakForm_Menu + 4;
Fl_Menu_Item* WindowConstructor::Stokes = WindowConstructor::menu_WeakForm_Menu + 5;
Fl_Menu_Item* WindowConstructor::NavierStokes = WindowConstructor::menu_WeakForm_Menu + 6;
Fl_Menu_Item* WindowConstructor::Poisson = WindowConstructor::menu_WeakForm_Menu + 7;
Fl_Menu_Item* WindowConstructor::L2Projection = WindowConstructor::menu_WeakForm_Menu + 8;

Fl_Menu_Item WindowConstructor::menu_surfaces[] = {
 {"exemplo Domain1", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"exemplo Domain2", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"exemplo Right", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"exemplo Left", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* WindowConstructor::EDomain1 = WindowConstructor::menu_surfaces + 0;
Fl_Menu_Item* WindowConstructor::EDomain2 = WindowConstructor::menu_surfaces + 1;
Fl_Menu_Item* WindowConstructor::ERight = WindowConstructor::menu_surfaces + 2;
Fl_Menu_Item* WindowConstructor::ELeft = WindowConstructor::menu_surfaces + 3;

Fl_Menu_Item WindowConstructor::menu_BounderyCondition[] = {
 {"Dirichlet", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Neumann", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Directional Homogeneous Dirichlet", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {"Directional Non-Homogeneous Dirichlet", 0,  0, 0, 0, (uchar)FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* WindowConstructor::Dirichlet = WindowConstructor::menu_BounderyCondition + 0;
Fl_Menu_Item* WindowConstructor::Neumann = WindowConstructor::menu_BounderyCondition + 1;
Fl_Menu_Item* WindowConstructor::DHDirichlet = WindowConstructor::menu_BounderyCondition + 2;
Fl_Menu_Item* WindowConstructor::DNHDirichlet = WindowConstructor::menu_BounderyCondition + 3;

/**
 Constructor
*/
WindowConstructor::WindowConstructor() {
  { Window = new Fl_Double_Window(1536, 793, "Window");
    Window->box(FL_BORDER_BOX);
    Window->user_data((void*)(this));
    { // Constains the geo and msh paths
      Container_1 = new Fl_Group(25, 45, 420, 190);
      Container_1->box(FL_BORDER_BOX);
      { msh_path = new Fl_Output(150, 115, 280, 35, "Input .msh Path:");
        msh_path->callback((Fl_Callback*)cb_msh_path);
      } // Fl_Output* msh_path
      { geo_path = new Fl_Output(150, 65, 280, 35, "Input .geo Path: ");
        geo_path->callback((Fl_Callback*)cb_geo_path);
      } // Fl_Output* geo_path
      { Save_paths = new Fl_Button(340, 185, 90, 25, "Save paths");
      } // Fl_Button* Save_paths
      { dimension = new Fl_Value_Output(180, 190, 50, 20, "Problem Dimension: ");
        dimension->color(FL_BACKGROUND2_COLOR);
      } // Fl_Value_Output* dimension
      Container_1->end();
    } // Fl_Group* Container_1
    { // Contains the Weak Form
      Container_2 = new Fl_Group(25, 260, 420, 285);
      Container_2->box(FL_BORDER_BOX);
      { WeakForm_Menu = new Fl_Choice(130, 280, 195, 25, "Weak Form:");
        WeakForm_Menu->box(FL_BORDER_BOX);
        WeakForm_Menu->down_box(FL_BORDER_BOX);
        WeakForm_Menu->menu(menu_WeakForm_Menu);
      } // Fl_Choice* WeakForm_Menu
      { surfaces = new Fl_Choice(130, 315, 195, 25, "Surfaces:");
        surfaces->down_box(FL_BORDER_BOX);
        surfaces->menu(menu_surfaces);
      } // Fl_Choice* surfaces
      { Apply_2 = new Fl_Button(320, 495, 90, 25, "Apply");
      } // Fl_Button* Apply_2
      { // Elasticity2D Variables
        Container_2_1 = new Fl_Group(45, 365, 365, 120);
        Container_2_1->box(FL_FLAT_BOX);
        Container_2_1->hide();
        { // Input Young Modulus for Elasticity2D
          E2D_young = new Fl_Value_Input(170, 370, 65, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* E2D_young
        { E2D_poisson = new Fl_Value_Input(170, 410, 65, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* E2D_poisson
        { E2D_PlaneStress = new Fl_Check_Button(45, 445, 25, 30, "Plane Stress ");
          E2D_PlaneStress->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* E2D_PlaneStress
        Container_2_1->end();
      } // Fl_Group* Container_2_1
      { // ElasticityPositional2D Variables
        Container_2_2 = new Fl_Group(45, 365, 355, 120);
        Container_2_2->box(FL_FLAT_BOX);
        Container_2_2->hide();
        { // Input Young Modulus for Elasticity2D
          EP2D_young = new Fl_Value_Input(170, 380, 45, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* EP2D_young
        { EP2D_poisson = new Fl_Value_Input(170, 420, 45, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* EP2D_poisson
        { EP2D_PlaneStress = new Fl_Check_Button(45, 455, 25, 0, "Plane Stress ");
          EP2D_PlaneStress->down_box(FL_DOWN_BOX);
        } // Fl_Check_Button* EP2D_PlaneStress
        Container_2_2->end();
      } // Fl_Group* Container_2_2
      { // Elasticity3D Variables
        Container_2_3 = new Fl_Group(45, 365, 355, 120);
        Container_2_3->box(FL_FLAT_BOX);
        Container_2_3->hide();
        { // Input Young Modulus for Elasticity2D
          E3D_young = new Fl_Value_Input(170, 370, 65, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* E3D_young
        { E3D_poisson = new Fl_Value_Input(170, 410, 65, 25, "Poisson Modulus:  ");
        } // Fl_Value_Input* E3D_poisson
        Container_2_3->end();
      } // Fl_Group* Container_2_3
      { // ElasticTruss Variables
        Container_2_4 = new Fl_Group(45, 365, 355, 120);
        Container_2_4->box(FL_FLAT_BOX);
        Container_2_4->hide();
        { // Input Young Modulus for Elasticity2D
          ET_young = new Fl_Value_Input(170, 370, 75, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* ET_young
        { ET_area = new Fl_Value_Input(170, 410, 75, 25, "Area: ");
        } // Fl_Value_Input* ET_area
        Container_2_4->end();
      } // Fl_Group* Container_2_4
      { // PositionalTruss Variables
        Container_2_5 = new Fl_Group(45, 365, 355, 120);
        Container_2_5->box(FL_FLAT_BOX);
        Container_2_5->hide();
        { PT_young = new Fl_Value_Input(170, 370, 65, 25, "Elasticity Modulus: ");
        } // Fl_Value_Input* PT_young
        { PT_area = new Fl_Value_Input(170, 410, 65, 25, "Area:   ");
        } // Fl_Value_Input* PT_area
        Container_2_5->end();
      } // Fl_Group* Container_2_5
      { // Stokes Variables
        Container_2_6 = new Fl_Group(45, 365, 355, 120);
        Container_2_6->box(FL_FLAT_BOX);
        Container_2_6->hide();
        { S_density = new Fl_Value_Input(170, 370, 65, 25, "Density: ");
        } // Fl_Value_Input* S_density
        { S_viscosity = new Fl_Value_Input(170, 410, 65, 25, "Viscosity: ");
        } // Fl_Value_Input* S_viscosity
        Container_2_6->end();
      } // Fl_Group* Container_2_6
      { // NavierStokes Variables
        Container_2_7 = new Fl_Group(45, 365, 355, 120);
        Container_2_7->box(FL_FLAT_BOX);
        Container_2_7->hide();
        { NS_density = new Fl_Value_Input(170, 370, 65, 25, "Density: ");
        } // Fl_Value_Input* NS_density
        { NS_viscosity = new Fl_Value_Input(170, 410, 65, 25, "Viscosity: ");
        } // Fl_Value_Input* NS_viscosity
        Container_2_7->end();
      } // Fl_Group* Container_2_7
      { // Poisson Variables
        Container_2_8 = new Fl_Group(45, 365, 355, 120);
        { P_nstate = new Fl_Value_Input(225, 370, 45, 25, "Number of State Variables: ");
          P_nstate->hide();
        } // Fl_Value_Input* P_nstate
        Container_2_8->end();
      } // Fl_Group* Container_2_8
      { // L2Projection Variables
        Container_2_9 = new Fl_Group(45, 355, 365, 130);
        Container_2_9->hide();
        { BounderyCondition = new Fl_Choice(185, 370, 190, 25, "Boundery Condition: ");
          BounderyCondition->down_box(FL_BORDER_BOX);
          BounderyCondition->menu(menu_BounderyCondition);
        } // Fl_Choice* BounderyCondition
        { valx = new Fl_Value_Input(75, 445, 70, 25, "X: ");
        } // Fl_Value_Input* valx
        { valy = new Fl_Value_Input(185, 445, 70, 25, "Y: ");
        } // Fl_Value_Input* valy
        { valz = new Fl_Value_Input(300, 445, 70, 25, "Z: ");
        } // Fl_Value_Input* valz
        { values = new Fl_Box(45, 415, 60, 25, "Values");
          values->color(FL_BACKGROUND2_COLOR);
        } // Fl_Box* values
        Container_2_9->end();
      } // Fl_Group* Container_2_9
      Container_2->end();
    } // Fl_Group* Container_2
    { // Contains the Script Output
      Container_3 = new Fl_Group(480, 45, 410, 680);
      Container_3->box(FL_BORDER_BOX);
      { // Shows updated applications 
        scroller = new Fl_Scroll(480, 45, 410, 625, "SCRIPT");
        scroller->box(FL_BORDER_BOX);
        scroller->color(FL_BACKGROUND2_COLOR);
        { scriptdisplay = new Fl_Text_Display(490, 55, 390, 605);
          scriptdisplay->box(FL_NO_BOX);
        } // Fl_Text_Display* scriptdisplay
        scroller->end();
      } // Fl_Scroll* scroller
      { Update_5 = new Fl_Button(775, 685, 105, 25, "Uptade Script");
      } // Fl_Button* Update_5
      Container_3->end();
    } // Fl_Group* Container_3
    { // Contains the visual tool
      Container_4 = new Fl_Group(920, 45, 570, 370);
      Container_4->box(FL_BORDER_BOX);
      Container_4->color(FL_BACKGROUND2_COLOR);
      Container_4->end();
    } // Fl_Group* Container_4
    Window->end();
  } // Fl_Double_Window* Window
}


#endif