// generated by Fast Light User Interface Designer (fluid) version 1.0309

#include "WindowConstructor.h"

/**
 Constructor
*/
WindowConstructor::WindowConstructor() {
  { Window = new Fl_Double_Window(795, 336, "Window");
    Window->box(FL_BORDER_BOX);
    // Window->user_data((this));
    /*{ WeakForm = new Fl_Choice(90, 25, 330, 30, "WeakForm");
      WeakForm->box(FL_BORDER_BOX);
      WeakForm->down_box(FL_BORDER_BOX);
    } // Fl_Choice* WeakForm*/
    Window->end();
  } // Fl_Double_Window* Window
}
